import Head from "next/head";
import UploadImage from "../components/Upload";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container max-w-screen-xl mx-auto">
				<h1>Hello World!</h1>
				<UploadImage />
			</main>
		</div>
	);
}
